demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('fanyi/',include('fanyi.urls',namespace='fanyi'))
]

demo1/fanyi/urls.py
from  django.conf.urls import url
from . import views

app_name='fanyi'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^fanyia/$',views.fanyia,name='fanyia'),
    url(r'^xiazai/$',views.xiazai,name='xiazai'),
]

demo1/fanyi/models.py
from django.db import models

# Create your models here.

demo1/fanyi/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponseRedirect,HttpResponse
from urllib import request
import requests
import urllib
import re
import time

# Create your views here.

def index(request):
    return render(request, 'fanyi/index.html')


def fanyia(request):
    try:
        if request.method=="POST":
            key = request.POST['keya']
            head = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' \
                              'AppleWebKit/537.36 (KHTML, like Gecko) ' \
                              'Chrome/74.0.3729.131 Safari/537.36'
            }
            url = 'http://fanyi.youdao.com/translate?smartresult=dict&smartresult=rul'
            formdate = {
                'i': key,
                'from': 'AUTO',
                'to': 'AUTO',
                'smartresult': 'dict',
                'client': 'fanyideskweb',
                'salt': '15573878832616',
                'sign': '5b2b7e8734c62ea56aafcae7a3c2a5fc',
                'ts': '1557387883261',
                'bv': '316dd52438d41a1d675c1d848edf4877',
                'doctype': 'json',
                'version': '2.1',
                'keyfrom': 'fanyi.web',
                'action': 'FY_BY_REALTlME'
            }

            date = urllib.parse.urlencode(formdate).encode(encoding='utf-8')

            # 有 date 就是post请求
            # 没有就是get请求
            req = request.Request(url, data=date, headers=head)

            resp = request.urlopen(req).read().decode()

            # 正则表达式，提取 "tgt":" 和 "} 中间的任意内容
            pat = r'"tgt":"(.*?)"}'

            result = re.findall(pat, resp)[0]
            print(result)
            return render(request,'fanyi/fanyi.html',{'result': result})
        elif request.method=="GET":
            return render(request,'fanyi/fanyi.html')
    except:
        return render(request, 'fanyi/fanyi.html')

def xiazai(request):
    songID = []
    songName = []
    for i in range(2):
        url = 'http://www.htqyy.com/top/musicList/hot?pageIndex=' + str(i) + '&pageSize=20'
        # print(url)
        # 获取音乐榜单的网页信息
        html = requests.get(url)
        strr = html.text
        # < span class ="title" > < a href="/play/108" target="play" title="牧羊曲" sid="108" > 牧羊曲 < / a > < / span >
        pat = r'title="(.*?)" sid' #匹配名字
        pat1 = r'sid="(.*?)"'  #匹配id
        idlist = re.findall(pat1, strr)
        titlelist = re.findall(pat, strr)
        songID.extend(idlist)
        songName.extend(titlelist)
    les=len(songName)
    les1=[]
    for i in range(les):
        les1.append(i)
    if request.method == "POST":
        gname= request.POST['sid']
        print(gname,'==========================')
        sid=songName.index(gname)
        print(sid,'=============================================')
        songurl = 'http://f2.htqyy.com/play7/' + str(sid) + '/mp3/5'
        songname = songName[sid]

        data = requests.get(songurl).content
        print('正在下载第', songname)

        with open('F:\\muc\\{}mp3'.format(songname), 'wb') as f:
            f.write(data)
        time.sleep(5)
        return render(request, 'fanyi/xiazai.html', {'songname': songName, 'songid': songID, 'les1': les})
    elif request.method == "GET":

        print(songName)
        print(songID)
        return render(request, 'fanyi/xiazai.html',{'songname':songName,'songid':songID,'les1':les})
    # for i in range(len(songID)):
    #     songurl = 'http://f2.htqyy.com/play7/' + str(i) + '/mp3/5'
    #     songname = songName[i]
    #
    #     data = requests.get(songurl).content
    #     print('正在下载第', i, '首----', songname)
    #
    #     with open('F:\\muc\\{}mp3'.format(songname), 'wb') as f:
    #         f.write(data)
    #     time.sleep(5)

demo1/templates/fanyi/fanyi.html
<html>
	<head>
		<meta charset="{CHARSET}">
		<title>龙哥翻译</title>
		<style type="text/css">
			#bao{
				width:500px;
				margin: 0 auto;
				background-color:aliceblue;
				border-radius: 10px;
				border:1px solid lightpink;
				align-content: center;
			}
			.top{
				font-size: 24px;
				color: lightskyblue;
				text-shadow:3px 2px 5px;
			}
			.jieguo{
				color: lightskyblue;
			}
		</style>
	</head>
	<body>
		<div id="bao">
			<p class="top">翻译是一门艺术，因为别人根本不知道你翻译的对错！</p>
			<form action="{% url 'fanyi:fanyia'  %}" method="post">
				<p>输入你想翻译</p>
				<textarea name="keya" id="" cols="30" rows="10"></textarea>
				<input type="submit" value="翻译"/>
			</form>
			<p>结果:</p>
			<p class="jieguo">{{result}}</p>
			<p><a href="{% url 'fanyi:index'  %}">返回首页</a></p>
		</div>

	</body>
</html>

demo1/templates/fanyi/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #bao{
				width:500px;
				margin: 0 auto;
				background-color:aliceblue;
				border-radius: 10px;
				border:1px solid lightpink;
				align-content: center;
		}
    </style>
</head>
<body>
<div id="bao">
    <p><a href="{% url 'fanyi:fanyia' %}">英汉互译</a></p>
    <p><a href="{% url 'fanyi:xiazai' %}">下载音乐</a></p>
</div>
</body>
</html>

demo1/templates/fanyi/xiazai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #bao{
				width:500px;
				margin: 0 auto;
				background-color:aliceblue;
				border-radius: 10px;
				border:1px solid lightpink;
				align-content: center;
		}
    </style>
</head>
<body>
<div id="bao">
    <p>下载音乐</p>
    <p><a href="{% url 'fanyi:index'  %}">返回首页</a></p>

    <ul>
        {% for i in songname %}
        <li>
            <form action="{% url 'fanyi:xiazai' %}" method="post">
                {{i}}
                <input type="hidden" value="{{i}}" name="sid" >
                <input type="submit" value="下载">
            </form>
        </li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'fanyi:index'  %}">返回首页</a></p>
</div>
</body>
</html>